staging-settings:
  user-workflow:
    workflow-name: "40x-staging"
    deployment-registry: "private"
  workflow-artifacts:
    workflow-path: "."
    config-path: "./config.staging.json"
    secrets-path: "./secrets.yaml"
